##########################################################
##
## 端口，app名字等应用基础配置
##
##########################################################
server:
  port: ${PORT:8080}
  servlet:
    context-path: /ut
  forward-headers-strategy: native
  error:
    include-message: always
  compression:
    enabled: true
spring:
  application:
    name: ut-app
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB
  ##########################################################
  ##
  ## http连接池配置
  ##
  ##########################################################
  http-client:
    pool:
      #连接池的最大连接数，0代表不限；如果取0，需要考虑连接泄露导致系统崩溃的后果
      max-total-connect: 1000
      #每个路由的最大连接数,如果只调用一个地址,可以将其设置为最大连接数
      max-connect-per-route: 200
      # 指客户端和服务器建立连接的超时时间,ms , 最大约21秒,因为内部tcp在进行三次握手建立连接时,默认tcp超时时间是20秒
      connect-timeout: 3000
      # 指客户端从服务器读取数据包的间隔超时时间,不是总读取时间,也就是socket timeout,ms
      read-timeout: 5000
      # 从连接池获取连接的timeout,不宜过大,ms
      connection-request-timout: 200
      # 重试次数
      retry-times: 3
      charset: UTF-8
      # 长连接保持时间 单位s,不宜过长
      keep-alive-time: 10

  ##########################################################
  ##
  ## mysql 数据源配置
  ##
  ##########################################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.116.231.110:3306/ut
    username: ut
    password: 7NcC8RHnyTRNEY4p
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 60000
      pool-name: DatebookHikariCP
      max-lifetime: 28740000
      #连接在连接池的最小生存时间（毫秒）
      connection-test-query: SELECT 1
  ##########################################################
  ##
  ## redis 数据源配置
  ##
  ##########################################################
  redis:
    host: 1.116.231.110
    database: 0
    port: 6379
    password: 6KbRAVKdTgXhEko0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

  ##########################################################
  ##
  ## freemarker 模板引擎配置
  ##
  ##########################################################
  freemarker:
    suffix: .ftl
    charset: UTF-8
    template-loader-path: classpath:/templates
    request-context-attribute: request


##########################################################
##
## mybatis-plus 配置
##
##########################################################
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
    # 是否显示mybatis-plus图标
    banner: false
  typeEnumsPackage: run.ut.app.model.enums
  configuration:
    # 关闭二级缓存
    cache-enabled: false
    # 单体应用可以开启一级缓存
    localCacheScope: SESSION
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

##########################################################
##
## websocket 配置
##
##########################################################
netty:
  websocket:
    port: 8088
    context-path: /ut/ws
    # 0表示自动设置，自动设置的值为：CPU核心数 * 2
    boss-threads: 0
    # 0表示自动设置，自动设置的值为：CPU核心数 * 2
    worker-threads: 0
    # 只能在linux和mac系统下才能设置为true，可以获得更高的性能
    epoll: false

##########################################################
##
## 日志 配置
##
##########################################################
logging:
  file:
    path: ${user.home}/.ut/logs
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 20
  level:
    run.ut.app.netty: debug
ut:
  download-timeout: 5m

