##########################################################
##
## 端口，app名字等应用基础配置
##
##########################################################
server:
  port: ${PORT:8080}
  servlet:
    context-path: /ut
spring:
  application:
    name: ut-app
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB
  ##########################################################
  ##
  ## http连接池配置
  ##
  ##########################################################
  http-client:
    pool:
      #连接池的最大连接数，0代表不限；如果取0，需要考虑连接泄露导致系统崩溃的后果
      max-total-connect: 1000
      #每个路由的最大连接数,如果只调用一个地址,可以将其设置为最大连接数
      max-connect-per-route: 200
      # 指客户端和服务器建立连接的超时时间,ms , 最大约21秒,因为内部tcp在进行三次握手建立连接时,默认tcp超时时间是20秒
      connect-timeout: 3000
      # 指客户端从服务器读取数据包的间隔超时时间,不是总读取时间,也就是socket timeout,ms
      read-timeout: 5000
      # 从连接池获取连接的timeout,不宜过大,ms
      connection-request-timout: 200
      # 重试次数
      retry-times: 3
      charset: UTF-8
      # 长连接保持时间 单位s,不宜过长
      keep-alive-time: 10

  ##########################################################
  ##
  ## mysql 数据源配置
  ##
  ##########################################################
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.156.14:3306/ut?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: ut
    password: 7NcC8RHnyTRNEY4p
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 60000
      pool-name: DatebookHikariCP
      max-lifetime: 28740000
      #连接在连接池的最小生存时间（毫秒）
      connection-test-query: SELECT 1
  ##########################################################
  ##
  ## redis 数据源配置
  ##
  ##########################################################
  redis:
    host: 47.101.156.14
    database: 0
    port: 6379
    password: 6KbRAVKdTgXhEko0
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

  ##########################################################
  ##
  ## freemarker 模板引擎配置
  ##
  ##########################################################
  freemarker:
    suffix: .ftl
    charset: UTF-8
    template-loader-path: classpath:/templates
    request-context-attribute: request


##########################################################
##
## mybatis-plus 配置
##
##########################################################
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
    # 是否显示mybatis-plus图标
    banner: false
  typeEnumsPackage: run.ut.app.model.enums
  # SQL 执行log，调试时可打开
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false

##########################################################
##
## 第三方sdk 配置
##
##########################################################
third-api-config:
  # 腾讯云短信验证码配置
  sms:
    # 应用 SDK AppID
    app-id: 1400274431
    # 应用 App Key
    app-key: 3fddda3db61f49ae02bd9c7de3dc56aa
    # 短信正文ID
    template-id: 448386
    # 短信签名
    sign: chen学习
    # 短信发送分钟间隔
    interval-min: 1
    # 短信有效分钟
    valid-min: 5

wechat:
  mp-app-id: wx0520203ba32fb247
  mp-app-secret: a211d5b68dc57636ccf1c9dce638e9e3
  authorize-url: https://api.weixin.qq.com/sns/jscode2session
  grant-type: authorization_code

logging:
  file:
    max-size: 10MB
    max-history: 20
    path: ${user.home}/.ut/logs
  level:
    run.ut.app: info
#    run.ut.app.core: debug
#    org.apache.http: debug
ut:
  download-timeout: 5m

