##########################################################
##
## 端口，app名字，dubbo，注册中心等应用基础配置
##
##########################################################
server:
  port: ${PORT:8080}
  servlet:
    context-path: /ut
spring:
  application:
    name: ut-bbs-service
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB
  ##########################################################
  ##
  ## http连接池配置
  ##
  ##########################################################
  http-client:
    pool:
      #连接池的最大连接数，0代表不限；如果取0，需要考虑连接泄露导致系统崩溃的后果
      max-total-connect: 1000
      #每个路由的最大连接数,如果只调用一个地址,可以将其设置为最大连接数
      max-connect-per-route: 200
      # 指客户端和服务器建立连接的超时时间,ms , 最大约21秒,因为内部tcp在进行三次握手建立连接时,默认tcp超时时间是20秒
      connect-timeout: 3000
      # 指客户端从服务器读取数据包的间隔超时时间,不是总读取时间,也就是socket timeout,ms
      read-timeout: 5000
      # 从连接池获取连接的timeout,不宜过大,ms
      connection-request-timout: 200
      # 重试次数
      retry-times: 3
      charset: UTF-8
      # 长连接保持时间 单位s,不宜过长
      keep-alive-time: 10

  ##########################################################
  ##
  ## freemarker 模板引擎配置
  ##
  ##########################################################
  freemarker:
    suffix: .ftl
    charset: UTF-8
    template-loader-path: classpath:/templates
    request-context-attribute: request

##########################################################
##
## dubbo 配置
##
##########################################################
dubbo:
  application:
    name: ut-bbs-service
  protocol:
    name: dubbo
    port: 12234
  registry:
    address: zookeeper://192.168.129.133:2181
    timeout: 60000
  consumer:
    timeout: 3000
  provider:
    timeout: 3000

##########################################################
##
## 日志 配置
##
##########################################################
logging:
  file:
    max-size: 10MB
    max-history: 20
    path: ${user.home}/.ut-bbs-service/logs
ut:
  download-timeout: 5m

