##########################################################
##
## 端口，app名字，dubbo，注册中心等应用基础配置
##
##########################################################
server:
  port: ${PORT:8084}
  servlet:
    context-path: /ut
spring:
  application:
    name: ut-gateway
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB
  ##########################################################
  ##
  ## cloud配置
  ##
  ##########################################################
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
      config:
        # 配置中心地址
        server-addr: 127.0.0.1:8848
        file-extension: yml

##########################################################
##
## 日志 配置
##
##########################################################
logging:
  file:
    max-size: 10MB
    max-history: 20
    path: ${user.home}/.ut-gateway/logs