##########################################################
##
## 端口，app名字，dubbo，注册中心等应用基础配置
##
##########################################################
server:
  port: ${PORT:8082}
  servlet:
    context-path: /ut
spring:
  application:
    name: ut-service-center
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB
  ##########################################################
  ##
  ## mysql 数据源配置
  ##
  ##########################################################
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.156.14:3306/ut?useUnicode=true&chatacterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: ut
    password: 7NcC8RHnyTRNEY4p
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 60000
      pool-name: DatebookHikariCP
      max-lifetime: 28740000
      #连接在连接池的最小生存时间（毫秒）
      connection-test-query: SELECT 1
  ##########################################################
  ##
  ## redis 数据源配置
  ##
  ##########################################################
  redis:
    host: 47.101.156.14
    database: 0
    port: 6379
    password: 6KbRAVKdTgXhEko0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

##########################################################
##
## dubbo 配置
##
##########################################################
dubbo:
  application:
    name: ut-service-center
  protocol:
    name: dubbo
    port: 12235
  registry:
    address: zookeeper://192.168.129.133:2181
    timeout: 60000

##########################################################
##
## mybatis-plus 配置
##
##########################################################
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
    # 是否显示mybatis-plus图标
    banner: false
  typeEnumsPackage: run.ut.app.model.enums
  configuration:
    # 关闭二级缓存
    cache-enabled: false
    # 非单体应用不可以开启一级缓存
    localCacheScope: STATEMENT

##########################################################
##
## websocket 配置
##
##########################################################
netty:
  websocket:
    port: 8088
    context-path: /ut/ws
    # 0表示自动设置，自动设置的值为：CPU核心数 * 2
    boss-threads: 0
    # 0表示自动设置，自动设置的值为：CPU核心数 * 2
    worker-threads: 0
    # 只能在linux和mac系统下才能设置为true，可以获得更高的性能
    epoll: false

##########################################################
##
## 日志 配置
##
##########################################################
logging:
  file:
    max-size: 10MB
    max-history: 20
    path: ${user.home}/.ut-service-center/logs
ut:
  download-timeout: 5m

