##########################################################
##
## 端口，app名字，dubbo，注册中心等应用基础配置
##
##########################################################
server:
  port: ${PORT:8081}
  servlet:
    context-path: /ut
spring:
  application:
    name: ut-chat-service
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB
  ##########################################################
  ##
  ## freemarker 模板引擎配置
  ##
  ##########################################################
  freemarker:
    suffix: .ftl
    chatset: UTF-8
    template-loader-path: classpath:/templates
    request-context-attribute: request

##########################################################
##
## dubbo 配置
##
##########################################################
dubbo:
  application:
    name: ut-chat-service
  protocol:
    name: dubbo
    port: 12233
  registry:
    address: zookeeper://192.168.129.133:2181
    timeout: 60000


##########################################################
##
## 日志 配置
##
##########################################################
logging:
  file:
    max-size: 10MB
    max-history: 20
    path: ${user.home}/.ut-chat-service/logs
ut:
  download-timeout: 5m

