##########################################################
##
## 端口，app名字，dubbo，注册中心等应用基础配置
##
##########################################################
server:
  port: ${PORT:8081}
spring:
  application:
    name: ut-chat-service
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
      config:
        # 配置中心地址
        server-addr: 127.0.0.1:8848
        # 配置文件格式
        file-extension: yml
##########################################################
##
## dubbo 配置
##
##########################################################
dubbo:
  application:
    name: ut-chat-service
  protocol:
    name: dubbo
    port: 12233
  registry:
    address: nacos://localhost:8848
    timeout: 60000
  consumer:
    check: false

##########################################################
##
## websocket 配置
##
##########################################################
netty:
  websocket:
    port: 8088
    context-path: /ws
    # 0表示自动设置，自动设置的值为：CPU核心数 * 2
    boss-threads: 0
    # 0表示自动设置，自动设置的值为：CPU核心数 * 2
    worker-threads: 0
    # 只能在linux和mac系统下才能设置为true，可以获得更高的性能
    epoll: false

##########################################################
##
## 日志 配置
##
##########################################################
logging:
  file:
    max-size: 10MB
    max-history: 20
    path: ${user.home}/.ut-chat-service/logs
ut:
  download-timeout: 5m

