##########################################################
##
## 端口，app名字，dubbo，注册中心等应用基础配置
##
##########################################################
server:
  port: ${PORT:8081}
  servlet:
    context-path: /ut
spring:
  application:
    name: ut-chat-service
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB

##########################################################
##
## dubbo 配置
##
##########################################################
dubbo:
  application:
    name: ut-chat-service
  protocol:
    name: dubbo
    port: 12233
  registry:
    address: zookeeper://192.168.129.133:2181
    timeout: 60000
  consumer:
    check: false

##########################################################
##
## websocket 配置
##
##########################################################
netty:
  websocket:
    port: 8088
    context-path: /ut/ws
    # 0表示自动设置，自动设置的值为：CPU核心数 * 2
    boss-threads: 0
    # 0表示自动设置，自动设置的值为：CPU核心数 * 2
    worker-threads: 0
    # 只能在linux和mac系统下才能设置为true，可以获得更高的性能
    epoll: false

##########################################################
##
## 日志 配置
##
##########################################################
logging:
  file:
    max-size: 10MB
    max-history: 20
    path: ${user.home}/.ut-chat-service/logs
ut:
  download-timeout: 5m

